name: devops-challenge

on: 
  push:
    branches:
      - 'develop'

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: '15.x'

      - name: Install Dependencies
        run: npm install

      - name: Install Dependencies
        run: npm install

      - name: Linter (ESLint)
        run: npm run lint

      - name: Formatter (Prettier)
        run: npm install -g prettier && npm run prettier -- --write

      - name: Test (Jest)
        env:
          CI: true
        run: npm run test

      - name: Build
        run: npm run build

  Docker: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/devops-callenge:${{ github.sha }} .

      - name: Push Docker image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-callenge:${{ github.sha }}
